### ISSUE TITLE
Invalid argument:  Input to reshape is a tensor with 307 values, but the requested shape requires a multiple of 14

### ISSUE THREAD

**Issue by faizan1041** [Tessellate-Imaging/Monk_Object_Detection#84]
Hi,

I'm using my own dataset to train the tf2 model. The tfrecord generation process went good, thought I went into a few issues initially but they were sorted out. Pasting the tfrecord generation and hyperparams code:

```
train_img_dir = f"{BASE_DIR}/images_rows_v4/train/img";
train_anno_dir = f"{BASE_DIR}/images_rows_v4/train/xml";
class_list_file = f"{BASE_DIR}/classes.txt";

gtf.set_train_dataset(train_img_dir, train_anno_dir, class_list_file, batch_size=4)


val_img_dir = f"{BASE_DIR}/images_rows_v4/test/img";
val_anno_dir = f"{BASE_DIR}/images_rows_v4/test/xml";

gtf.set_val_dataset(val_img_dir, val_anno_dir)

gtf.create_tfrecord(data_output_dir=f"{BASE_DIR}/data_tfrecord")


gtf.set_model_params(model_name="ssd_resnet50_v1_fpn_640")
gtf.set_hyper_params(num_train_steps=100000, lr=0.03)

gtf.export_params(output_directory=f"{BASE_DIR}/export_dir2");
```

This generated the tfrecords and when I run the following script: 
`python 13_tf_obj_2/lib/train.py`

I get the following errors:

```
Traceback (most recent call last):
  File "13_tf_obj_2/lib/train.py", line 47, in <module>
    tf.compat.v1.app.run(main=main)         
  File "/home/faizan/code/computer_vision/Monk_Object_Detection/env/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/faizan/code/computer_vision/Monk_Object_Detection/env/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/faizan/code/computer_vision/Monk_Object_Detection/env/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "13_tf_obj_2/lib/train.py", line 45, in main
    record_summaries=args_["record_summaries"])
  File "/home/faizan/code/computer_vision/Monk_Object_Detection/13_tf_obj_2/lib/models/research/object_detection/model_lib_v2.py", line 631, in train_loop
    loss = _dist_train_step(train_input_iter)
  File "/home/faizan/code/computer_vision/Monk_Object_Detection/env/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/home/faizan/code/computer_vision/Monk_Object_Detection/env/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 807, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/home/faizan/code/computer_vision/Monk_Object_Detection/env/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/faizan/code/computer_vision/Monk_Object_Detection/env/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/home/faizan/code/computer_vision/Monk_Object_Detection/env/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/faizan/code/computer_vision/Monk_Object_Detection/env/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/home/faizan/code/computer_vision/Monk_Object_Detection/env/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  Input to reshape is a tensor with 307 values, but the requested shape requires a multiple of 14
	 [[{{node Reshape_5}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNext]]
	 [[Loss/classification_loss_1/write_summary/ReadVariableOp/_48]]
  (1) Invalid argument:  Input to reshape is a tensor with 307 values, but the requested shape requires a multiple of 14
	 [[{{node Reshape_5}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored. [Op:__inference__dist_train_step_35102]

Function call stack:
_dist_train_step -> _dist_train_step

```

Also, I tried setting the batch_size to 1. I have following gpu configs:

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.45.01    Driver Version: 455.45.01    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro K2200        On   | 00000000:04:00.0 Off |                  N/A |
| 42%   27C    P8     1W /  39W |     11MiB /  4043MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 1070    On   | 00000000:05:00.0  On |                  N/A |
|  0%   42C    P2    31W / 151W |    583MiB /  8118MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

**Comment by abhi-kumar** [comment]
Thank you for trying out monk. I am glad you found it useful. I will soon look into the error. The development of the library is a little slow these days due to some personal work. I will try my best to find a solution soon.

**Comment by faizan1041** [comment]
Actually, the number of classes was wrong in val.record as the those images didn't have the classes which were in the 'train' set. This was resolved after adding more examples in 'val' set so that we have right number of classes there as well. 

Another thing noticed is that whenever I generate the tfrecords with the script over here: `gtf.create_tfrecord` I face the same issue again. But when I generate it with the script from my TF1 script which I have been using, the training works. So, seems like the issue is with the tfrecord script from this repo.
